<?php
declare(strict_types=1);

return [
    'defects' => [
        'name' => 'Defect Tracker',
        'short_name' => 'Defects',
        'description' => 'Raise, assign and close defects with drawings, photos and field evidence.',
        'url' => 'https://mcgoff.defecttracker.uk',
        'health_url' => 'https://mcgoff.defecttracker.uk/health.php',
        'icon' => 'defects',
        'accent' => 'blue',
        'offline' => 'Field mode',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 10,
    ],
    'deliveries' => [
        'name' => 'Site Deliveries',
        'short_name' => 'Deliveries',
        'description' => 'Coordinate delivery bookings, logistics slots and gate activity.',
        'url' => 'https://deliveries.defecttracker.uk',
        'icon' => 'truck',
        'accent' => 'orange',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 20,
    ],
    'safety' => [
        'name' => 'Safety Tours',
        'short_name' => 'Safety',
        'description' => 'Capture site observations and turn safety tours into clear actions.',
        'url' => 'https://safety.defecttracker.uk',
        'health_url' => 'https://safety.defecttracker.uk/health.php?format=json',
        'icon' => 'shield',
        'accent' => 'green',
        'offline' => 'PWA enabled',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 30,
    ],
    'permits' => [
        'name' => 'Permits',
        'short_name' => 'Permits',
        'description' => 'Organise permits and keep controlled work ready for safe approval.',
        'url' => 'https://permits.defecttracker.uk',
        'icon' => 'permit',
        'accent' => 'purple',
        'offline' => 'PWA enabled',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 40,
    ],
    'documents' => [
        'name' => 'Site Documents',
        'short_name' => 'Documents',
        'description' => 'Create, issue and close site notices with offline document working.',
        'url' => 'https://docs.defecttracker.uk',
        'icon' => 'document',
        'accent' => 'violet',
        'offline' => 'Offline ready',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 50,
    ],
    'handover' => [
        'name' => 'Handover',
        'short_name' => 'Handover',
        'description' => 'Keep commissioning, certificates, evidence and project close-out together.',
        'url' => 'https://handover.defecttracker.uk',
        'icon' => 'check',
        'accent' => 'cyan',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 60,
    ],
    'programme' => [
        'name' => 'Programme',
        'short_name' => 'Programme',
        'description' => 'Track construction activities, lookaheads and apartment progress.',
        'url' => 'https://programme.defecttracker.uk',
        'icon' => 'calendar',
        'accent' => 'amber',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 70,
    ],
    'status' => [
        'name' => 'Service Status',
        'short_name' => 'Status',
        'description' => 'Check availability and health across the construction toolset.',
        'url' => 'https://status.defecttracker.uk',
        'icon' => 'pulse',
        'accent' => 'slate',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['platform_admin', 'admin', 'manager', 'site_manager'],
        'sort' => 80,
    ],
];
