
<?php

return [
    'defects' => [
        'name' => 'Defect Tracker',
        'short_name' => 'Defects',
        'description' => 'Raise, assign and close defects with drawings, photos and field evidence.',
        'url' => 'https://defectnotice.site',
        'health_url' => 'https://defectnotice.site/health.php',
        'summary_url' => 'https://defectnotice.site/api/suite-summary.php',
        'reference_url' => 'https://defectnotice.site/api/suite-references.php',
        'summary_param' => 'project',
        'summary_requires_ref' => true,
        'summary_allow_all' => true,
        'icon' => 'defects',
        'accent' => 'blue',
        'offline' => 'Field mode',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 10,
    ],
    'deliveries' => [
        'name' => 'Site Deliveries',
        'short_name' => 'Deliveries',
        'description' => 'Coordinate delivery bookings, logistics slots and gate activity.',
        'url' => 'https://sitedeliveries.site',
        'icon' => 'truck',
        'accent' => 'orange',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 20,
    ],
    'safety' => [
        'name' => 'Safety Tours',
        'short_name' => 'Safety',
        'description' => 'Capture site observations and turn safety tours into clear actions.',
        'url' => 'https://sitesafety.site',
        'health_url' => 'https://sitesafety.site/health.php?format=json',
        'summary_url' => 'https://sitesafety.site/api/suite-summary.php',
        'reference_url' => 'https://sitesafety.site/api/suite-references.php',
        'summary_param' => 'site',
        'summary_requires_ref' => true,
        'summary_allow_all' => true,
        'icon' => 'shield',
        'accent' => 'green',
        'offline' => 'PWA enabled',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 30,
    ],
    'permits' => [
        'name' => 'Site Permits',
        'short_name' => 'Permits',
        'description' => 'Organise permits and keep controlled work ready for safe approval.',
        'url' => 'https://sitepermits.site',
        'summary_url' => 'https://sitepermits.site/api/suite-summary.php',
        'reference_url' => 'https://sitepermits.site/api/suite-references.php',
        'summary_param' => 'site',
        'summary_requires_ref' => true,
        'summary_allow_all' => true,
        'icon' => 'permit',
        'accent' => 'purple',
        'offline' => 'PWA enabled',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 40,
    ],
    'documents' => [
        'name' => 'Site Notices',
        'short_name' => 'Notices',
        'description' => 'Manage site notices, cleanup actions, close-out evidence and offline working.',
        'url' => 'https://sitenotices.site',
        'icon' => 'document',
        'accent' => 'violet',
        'offline' => 'Offline ready',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 50,
    ],
    'handover' => [
        'name' => 'Handover',
        'short_name' => 'Handover',
        'description' => 'Keep commissioning, certificates, evidence and project close-out together.',
        'url' => 'https://handover.defecttracker.uk',
        'icon' => 'check',
        'accent' => 'cyan',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 60,
    ],
    'programme' => [
        'name' => 'Programme',
        'short_name' => 'Programme',
        'description' => 'Track construction activities, lookaheads and apartment progress.',
        'url' => 'https://programme.defecttracker.uk',
        'icon' => 'calendar',
        'accent' => 'amber',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => ['*'],
        'sort' => 70,
    ],
    'status' => [
        'name' => 'Service Status',
        'short_name' => 'Status',
        'description' => 'Check availability and health across the construction toolset.',
        'url' => 'https://status.defecttracker.uk',
        'icon' => 'pulse',
        'accent' => 'slate',
        'offline' => 'Online module',
        'enabled' => true,
        'roles' => [
            'platform_admin',
            'admin',
            'manager',
            'site_manager'
        ],
        'sort' => 80,
    ],
];
